import Head from "next/head";
import React from "react";
import { Merriweather } from "next/font/google";
import { api } from "~/utils/api";

const font = Merriweather({
  weight: ["400", "700"],
  subsets: ["latin-ext"],
});

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const [topic, setTopic] = React.useState("dog");

  return (
    <>
      <Head>
        <title>Response Steaming</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={font.className}>
        <div className="nav-root bg-sky-800 py-4">
          <nav className="container mx-auto flex max-w-screen-2xl items-center">
            <span className="text-xl text-white">
              React - Response Streaming
            </span>
          </nav>
        </div>
        <main className="container mx-auto max-w-screen-2xl py-10">
          <h1 className="mb-4 text-2xl font-bold">
            Generate a story about something
          </h1>
          <p>
            Tell me a story about a{" "}
            <input
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              className="ml-1 inline-block w-28 rounded border p-2"
            />
          </p>
        </main>
      </div>
    </>
  );
}
